export * from "./Categorias";
export * from "./Modal";
export * from "./Word";
export * from "./Videos";
export * from "./Paciente";
export * from "./Paciente2";
export * from "./LoaderPatient";
export * from "./Oraciones";
export * from "./Usuarios";
